document.write("<section>");
document.write("<h1> Toda la Información </h1>");
document.write("<p> Nombre: ");
document.write(info.nombre);
document.write("</p>");
document.write("<p> Plataforma: ");
document.write(info.plataforma);
document.write("</p>");
document.write("<p> Vendedor: ");
document.write(info.vendedor);
document.write("</p>");
document.write("<p> Agente: ");
document.write(info.agente);
document.write("</p>");
document.write("<p> Versión: ");
document.write(info.version);
document.write("</p>");
document.write("<p> Java Activado: ");
document.write(info.java);
document.write("</p>");
document.write("</section>");